### ISSUE TITLE
rename to txexiftool

### ISSUE THREAD

**Issue by glyph** [znerol/twisted-exiftool#1]
Hi @znerol ,

Thanks for using Twisted.  This looks interesting :).

In order to avoid confusing users about what's "official" or not, and to help the Software Freedom Conservancy (Twisted's fiscal sponsor) retain a clear trademark on the term "Twisted" as applied to the Twisted software, we like to ask that all community projects use "Tx" as a prefix so it's clear what comes within Twisted ("twisted.foo", or "Twisted Foo") and what comes from third parties ("txfoo").  This is sort of like the `py` prefix that a lot of 3rd-party Python projects adopt.

If you could rename twisted-exiftool to `txexiftool` that would be more consistent with lots of other projects, and would also help us protect the Twisted trademark from dilution in case we ever have to protect it from somebody using it in a truly misleading or harmful way.

Thanks!

**Comment by glyph** [comment]
Thank you for the incredibly quick reply!

**Comment by znerol** [comment]
Sure. I was not aware of that naming convention. I quickly checked on pypi but obviously failed to scroll down to the contributed projects with the correct prefix...
